In [1]:
import pandas as pd

In [3]:
npr = pd.read_csv("C:/Users/mayur/Downloads/archive (11)/npr.csv")

In [4]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv =CountVectorizer(max_df=0.9,min_df=2,stop_words="english")

In [8]:
dm =cv.fit_transform(npr['Article'])

In [9]:
dm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

In [12]:
lda = LatentDirichletAllocation(n_components=7,random_state=42)

In [13]:
lda.fit(dm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [16]:
len(cv.get_feature_names())

C:\Users\mayur\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


54777

In [18]:
type(cv.get_feature_names())

C:\Users\mayur\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


list

In [19]:
cv.get_feature_names()[4000]

C:\Users\mayur\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


'atizado'

In [23]:
import random


In [29]:
rwid=random.randint(0,5000)
cv.get_feature_names()[rwid]

'alissa'

In [30]:
len(lda.components_)

7

In [31]:
type(lda.components_)

numpy.ndarray

In [32]:
lda.components_.shape

(7, 54777)

In [33]:
lda.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [34]:
single_topic = lda.components_[0]

In [35]:
single_topic.argsort() # argsort returns index position sorted in ascending order

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [38]:
top_ten_words=single_topic.argsort()[-10:] # 10 greatest values

In [39]:
for i in top_ten_words:
    print(cv.get_feature_names()[i])

C:\Users\mayur\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


new
percent
government
company
million
care
people
health
said
says


In [44]:
for i,topic in enumerate(lda.components_):
    print(f"top 15 words are:{i}")
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print("\n")

top 15 words are:0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


top 15 words are:1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


top 15 words are:2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


top 15 words are:3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


top 15 words are:4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


top 15 words are:5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']


top 15 words are:6
['student', 'years

In [45]:
topic_results = lda.transform(dm)

In [47]:
topic_results.shape

(11992, 7)

In [49]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [50]:
topic_results[0].argmax()

1

In [53]:
npr['topic'] = topic_results.argmax(axis=1)

In [54]:
npr

Article  topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]